version: '3.8'

services:
  mariadb:
    build: requirements/mariadb/
    image: mariadb
    container_name: mariadb
    restart: unless-stopped
    env_file: .env
    volumes:
      - dbdata:/var/lib/mysql
    networks:
      - inception

  wordpress:
    build: requirements/wordpress/
    depends_on:
      - mariadb
    image: wordpress
    container_name: wordpress
    restart: unless-stopped
    env_file: .env
    volumes:
      - wordpress:/var/www/wordpress
    networks:
      - inception

  nginx:
    build: requirements/nginx/
    depends_on:
      - wordpress
    image: nginx
    container_name: nginx
    restart: unless-stopped
    volumes:
      - wordpress:/var/www/wordpress
    ports:
      - "443:443"
    networks:
      - inception

volumes:
  dbdata:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: /home/oheinzel/data/wp_database
  wordpress:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: /home/oheinzel/data/wp_files

networks:
  inception:
    driver: bridge
