version: '3.8'

services:
  mariadb:
    build: requirements/mariadb/
    image: mariadb
    container_name: mariadb
    restart: unless-stopped
    env_file: .env
    volumes:
      - dbdata:/var/lib/mysql
    ports:
      - "3306"
    networks:
      - app-network

  wordpress:
    build: requirements/wordpress/
    depends_on:
      - mariadb
    image: wordpress
    container_name: wordpress
    restart: unless-stopped
    env_file: .env
    volumes:
      - wordpress:/var/www/wordpress
    ports:
      - "9000"
    networks:
      - app-network

  nginx:
    build: requirements/nginx/
    depends_on:
      - wordpress
    image: nginx
    container_name: nginx
    restart: unless-stopped
    volumes:
      - wordpress:/var/www/wordpress
    ports:
      - "443:443"
    networks:
      - app-network

volumes:
  dbdata:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: /home/oheinzel/data/wpdata
  wordpress:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: /home/oheinzel/data/wpfiles

networks:
  app-network:
    # driver: bridge
